name: 'Install luamake'
description: 'Installs luamake and adds it to the path'
inputs:
  arch:
    description: Target architecture(only msvc)
    default: x64
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/index.js'
