name: 'Install luamake'
description: 'Installs luamake and adds it to the path'
inputs:
  ref:
    description: The branch, tag or SHA to checkout.
    default: master
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'node20'
  main: 'dist/index.js'
