name: test
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-20.04, ubuntu-22.04, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: ./
    - run: luamake help
