name: test
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        - windows-11-arm
        - ubuntu-22.04
        - ubuntu-24.04
        - ubuntu-22.04-arm
        - ubuntu-24.04-arm
        - macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
    - run: luamake help
